package GUI.Loan_GUI;

import GUI.Book_GUI.bookAdd;
import GUI.Borrower_GUI.borrowersAdd;
import GUI.DatabaseConnection;
import desktop.models.Book;
import desktop.models.Borrower;
import desktop.models.Loan;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class loanAdd extends javax.swing.JFrame {

    public loanAdd() {
        initComponents();
        addHoverEffect(submit_btn);
    }
     DatabaseConnection db = new DatabaseConnection();
    ArrayList<Book> books = new ArrayList<>();
    ArrayList<Borrower> borrowers = new ArrayList<>();
    
    private void addHoverEffect(javax.swing.JButton button) {
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {
                button.setBackground(new Color(100, 80, 60));  // Hover color
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                button.setBackground(new Color(159,105,50));  // Original color
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        back_btn4 = new javax.swing.JButton();
        borrower_lbl4 = new javax.swing.JLabel();
        book_lbl = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        book_ComboBox = new javax.swing.JComboBox<>();
        borrower_ComboBox = new javax.swing.JComboBox<>();
        startDate_lbl2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(38, 39, 43));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(560, 400));
        jPanel6.setMinimumSize(new java.awt.Dimension(560, 400));
        jPanel6.setPreferredSize(new java.awt.Dimension(560, 400));

        jScrollPane5.setBorder(null);

        jTextPane5.setEditable(false);
        jTextPane5.setBackground(new java.awt.Color(38, 39, 43));
        jTextPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jTextPane5.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(159, 105, 50));
        jTextPane5.setText("LOAN");
        jTextPane5.setAutoscrolls(false);
        jTextPane5.setSelectedTextColor(new java.awt.Color(159, 105, 50));
        jScrollPane5.setViewportView(jTextPane5);

        back_btn4.setBackground(new java.awt.Color(159, 105, 50));
        back_btn4.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        back_btn4.setForeground(new java.awt.Color(255, 255, 255));
        back_btn4.setText("<");
        back_btn4.setBorderPainted(false);
        back_btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn4.setIconTextGap(1);
        back_btn4.setMargin(new java.awt.Insets(1, 5, 1, 5));
        back_btn4.setPreferredSize(new java.awt.Dimension(40, 30));
        back_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn4ActionPerformed(evt);
            }
        });

        borrower_lbl4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        borrower_lbl4.setForeground(new java.awt.Color(255, 255, 255));
        borrower_lbl4.setText("Borrower :");

        book_lbl.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        book_lbl.setForeground(new java.awt.Color(255, 255, 255));
        book_lbl.setText("Book :");

        submit_btn.setBackground(new java.awt.Color(159, 105, 50));
        submit_btn.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("SUBMIT");
        submit_btn.setBorderPainted(false);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        book_ComboBox.setBackground(new java.awt.Color(153, 153, 153));
        book_ComboBox.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        book_ComboBox.setPreferredSize(new java.awt.Dimension(240, 23));

        borrower_ComboBox.setBackground(new java.awt.Color(153, 153, 153));
        borrower_ComboBox.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        borrower_ComboBox.setPreferredSize(new java.awt.Dimension(240, 23));

        startDate_lbl2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        startDate_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        startDate_lbl2.setText("Start Date:");
        startDate_lbl2.setToolTipText("");

        jDateChooser1.setBackground(new java.awt.Color(153, 153, 153));
        jDateChooser1.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        jDateChooser1.setPreferredSize(new java.awt.Dimension(240, 23));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(book_lbl)
                            .addComponent(borrower_lbl4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startDate_lbl2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(book_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrower_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(back_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(submit_btn)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(book_lbl))
                            .addComponent(book_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borrower_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrower_lbl4)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(back_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDate_lbl2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(submit_btn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn4ActionPerformed
        this.dispose();
        new loansCRUD().setVisible(true);
    }//GEN-LAST:event_back_btn4ActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // Adds to the loan to the database
         if(book_ComboBox.getSelectedIndex() == 0 || borrower_ComboBox.getSelectedIndex() == 0 || jDateChooser1.getDate() == null)
        {
            JOptionPane.showMessageDialog(this, "Please fill in all fields and choose an author and a genre please");
        }
        else{
            int bookIndex = book_ComboBox.getSelectedIndex() - 1;
            Book book = books.get(bookIndex);
            int borrowerIndex = borrower_ComboBox.getSelectedIndex() - 1;
            Borrower borrower = borrowers.get(borrowerIndex);
            
            java.util.Date selectedDate = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
            
            Loan loan = new Loan(book.getBookID(), borrower.getLibraryCardID(), sqlDate);
            
            db.addLoan(loan);
            

            
            book_ComboBox.setSelectedIndex(0);
            borrower_ComboBox.setSelectedIndex(0);
            jDateChooser1.setDate(null);
            
             JOptionPane.showMessageDialog(this, "Loan added successfully!");        
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        book_ComboBox.removeAllItems();
        book_ComboBox.addItem("Select Book");

        try {
            db.connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(bookAdd.class.getName()).log(Level.SEVERE, null, ex);
        }

        books = db.Bookview();
        for(Book book : books){
            book_ComboBox.addItem(book.getTitle() + " " + book.getStatus());
        }

        borrower_ComboBox.removeAllItems();
        borrower_ComboBox.addItem("Select Borrower");
        
        try {
            db.connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(borrowersAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        borrowers = db.Borrowerview();
        for(Borrower borrower : borrowers){
            book_ComboBox.addItem(borrower.getName()+ " " + borrower.getSurname());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn4;
    private javax.swing.JComboBox<String> book_ComboBox;
    private javax.swing.JLabel book_lbl;
    private javax.swing.JComboBox<String> borrower_ComboBox;
    private javax.swing.JLabel borrower_lbl4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JLabel startDate_lbl2;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
