package GUI;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class loansCRUD extends javax.swing.JFrame {


    public loansCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookBody = new javax.swing.JPanel();
        addLoan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        deleteLoan = new javax.swing.JButton();
        viewLoans = new javax.swing.JButton();
        editLoan = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Loans");
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);

        bookBody.setBackground(new java.awt.Color(38, 39, 43));
        bookBody.setPreferredSize(new java.awt.Dimension(900, 420));
        bookBody.setRequestFocusEnabled(false);

        addLoan.setBackground(new java.awt.Color(78, 66, 52));
        addLoan.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        addLoan.setForeground(new java.awt.Color(255, 255, 255));
        addLoan.setText("Add Loan");
        addLoan.setAlignmentX(0.5F);
        addLoan.setBorderPainted(false);
        addLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLoan.setFocusPainted(false);
        addLoan.setFocusable(false);
        addLoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addLoan.setMargin(new java.awt.Insets(2, 14, 2, 14));
        addLoan.setName("addLoan"); // NOI18N
        addLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTextPane1.setBackground(new java.awt.Color(38, 39, 43));
        jTextPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jTextPane1.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(159, 105, 50));
        jTextPane1.setText("MANAGE LOANS");
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTextPane1.setSelectedTextColor(new java.awt.Color(159, 105, 50));
        jScrollPane1.setViewportView(jTextPane1);

        deleteLoan.setBackground(new java.awt.Color(78, 66, 52));
        deleteLoan.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        deleteLoan.setForeground(new java.awt.Color(255, 255, 255));
        deleteLoan.setText("Delete Loan");
        deleteLoan.setAlignmentY(0.0F);
        deleteLoan.setBorderPainted(false);
        deleteLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLoan.setFocusPainted(false);
        deleteLoan.setFocusable(false);
        deleteLoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteLoan.setMargin(new java.awt.Insets(2, 14, 2, 14));
        deleteLoan.setName("deleteLoan"); // NOI18N
        deleteLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLoanActionPerformed(evt);
            }
        });

        viewLoans.setBackground(new java.awt.Color(78, 66, 52));
        viewLoans.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        viewLoans.setForeground(new java.awt.Color(255, 255, 255));
        viewLoans.setText("View Loans");
        viewLoans.setAlignmentX(0.5F);
        viewLoans.setBorderPainted(false);
        viewLoans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLoans.setFocusPainted(false);
        viewLoans.setFocusable(false);
        viewLoans.setMargin(new java.awt.Insets(2, 14, 2, 14));
        viewLoans.setName("viewLoans"); // NOI18N
        viewLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoansActionPerformed(evt);
            }
        });

        editLoan.setBackground(new java.awt.Color(78, 66, 52));
        editLoan.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        editLoan.setForeground(new java.awt.Color(255, 255, 255));
        editLoan.setText("Edit Loan");
        editLoan.setAlignmentX(0.5F);
        editLoan.setBorderPainted(false);
        editLoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editLoan.setFocusPainted(false);
        editLoan.setFocusable(false);
        editLoan.setMargin(new java.awt.Insets(2, 14, 2, 14));
        editLoan.setName("editLoan"); // NOI18N
        editLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLoanActionPerformed(evt);
            }
        });

        Backbtn.setBackground(new java.awt.Color(159, 105, 50));
        Backbtn.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("<");
        Backbtn.setBorderPainted(false);
        Backbtn.setFocusPainted(false);
        Backbtn.setFocusable(false);
        Backbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Backbtn.setIconTextGap(1);
        Backbtn.setMargin(new java.awt.Insets(1, 5, 1, 5));
        Backbtn.setPreferredSize(new java.awt.Dimension(40, 30));
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookBodyLayout = new javax.swing.GroupLayout(bookBody);
        bookBody.setLayout(bookBodyLayout);
        bookBodyLayout.setHorizontalGroup(
            bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookBodyLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(bookBodyLayout.createSequentialGroup()
                        .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editLoan, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(viewLoans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130))))
        );
        bookBodyLayout.setVerticalGroup(
            bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookBodyLayout.createSequentialGroup()
                .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookBodyLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(bookBodyLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(bookBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLoanActionPerformed

    private void editLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editLoanActionPerformed

    private void deleteLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLoanActionPerformed

    private void viewLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewLoansActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        this.dispose();
        new maindashboard().setVisible(true);
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loansCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loansCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loansCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loansCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loansCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton addLoan;
    private javax.swing.JPanel bookBody;
    private javax.swing.JButton deleteLoan;
    private javax.swing.JButton editLoan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton viewLoans;
    // End of variables declaration//GEN-END:variables
}
